/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ICurveFunctions } from "./ICurveFunctions";

export class ICurveFunctionsFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurveFunctions {
    return new Contract(address, _abi, signerOrProvider) as ICurveFunctions;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256"
      }
    ],
    name: "curveIntegral",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "pure",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256"
      }
    ],
    name: "inverseCurveIntegral",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "pure",
    type: "function"
  }
];
